TOMDOCSH := tomdoc.sh

all:

doc: all
	{ printf "# Sharness API\n\n"; \
	  $(TOMDOCSH) -m -a Public sharness.sh; \
	  printf "Generated by "; $(TOMDOCSH) --version; } >API.md

test: all
	$(MAKE) -C test

.PHONY: all doc test
