name: Tests

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      env:
        TEST_OPTS: -v
        MSYS: winsymlinks:nativestrict
      run: make test
